### ISSUE TITLE
Incluir filtros para eventos e defesas

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/eventos#12]
Nas visões de eventos e defesas, incluir filtros para mostrar "próximas", "passadas" e "não agendadas"

**Comment by ayrtonnotrya** [comment]
O cadastro e edição de evento exige data e horário, não existe uma categoria de eventos não agendados.

**Comment by ayrtonnotrya** [comment]
foi atendido nos commits ef622a3b95342d1e8d7b9fe6a8e84929e945b99d 400665d146ba1d5eda7cb927992a0c1db178589a 4dfcf4766efc904b26986789c9ebe5280a90bf08

**Comment by marcelomodesto** [comment]
Ao abrir a página, é melhor não apresentar nenhuma defesa. O ideal é apresentar somente quando a pessoa clica na opção.
