### ISSUE TITLE
Criar interface pública para listar os próximos eventos

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/eventos#2]

**Comment by ayrtonnotrya** [comment]
Foi atendido no commit 8633ffae59ab1cee68c9027b98a4bb06bd87aaf8

**Comment by marcelomodesto** [comment]
A interface pública precisa apresentar os detalhes. Pode ser um link sobre cada item que remete para o detalhe de cada evento.

**Comment by marcelomodesto** [comment]
o mesmo da issue #13
