### ISSUE TITLE
horário de um evento de vários dias está aparecendo errado na página

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/eventos#23]
o horário do evento amostra da estatistica (21 a 25/11 das 9 às 18 horas) está aparecendo errado na página inicial do Instituto

**Comment by ayrtonnotrya** [comment]
Verifiquei o evento e o que está cadastrado no sistema de eventos é o que aparece no site do ime:
![Screenshot from 2022-11-20 17-05-34](https://user-images.githubusercontent.com/28987938/202923769-83699970-6b61-436b-aa2d-a4e941e79acb.png)

![Screenshot from 2022-11-20 17-06-08](https://user-images.githubusercontent.com/28987938/202923775-b3048e7b-eaf8-43dd-b616-3fc304f7f902.png)
