### ISSUE TITLE
Exibição da instituição dos membros de banca não aparece na interface depois de cadastrado

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/eventos#28]

**Comment by ayrtonnotrya** [comment]
![Screenshot from 2023-01-18 09-19-16](https://user-images.githubusercontent.com/28987938/213169889-91bc840a-fe3d-4db7-8008-ac0664395016.png)
![Screenshot from 2023-01-18 09-18-05](https://user-images.githubusercontent.com/28987938/213169918-3dbb6653-b3c9-458c-b1e5-a8de115a60f9.png)

Tanto no site do IME como no Sistema de Eventos está aparecendo a instituição.

Poderia dar um exemplo, ou dizer em qual caso não esta aparecendo?
