### ISSUE TITLE
Cadastro de datas não está funcionando adequadamente

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/eventos#6]
No firefox,  os campos de horários não aceitam os valores preenchidos. É interessante verificar a configuração do componente ou alterar para um que funcione em qualquer navegador ou alterar por um campo de entrada simples.

**Comment by ayrtonnotrya** [comment]
Pelo que eu pesquisei alguns navegadores pegam o formato de horas das configurações do sistema operacional, podendo ser 24h ou 12AMPM, e não é possível forçar o formato. Aparentemente o tamanho do campo estava escondendo o AMPM, o que pode ter induzido o erro, para contornar isso aumentei o tamanho do campo(commit bc409c1454bc3004aebfbb809ba3710e2c7afdff), acredito que ficou mais nítido qual formato o navegador esta usando.

**Comment by ayrtonnotrya** [comment]
foi atendido no commit 93576a7697c26ed88a9c9d21113527e9cd7b2008
